### ISSUE TITLE
Loading weights

### ISSUE THREAD

**Issue by gravity1989** [baumgach/SonoNet-weights#1]
Hi,

Could you help me load the weights so that I can pass new images through the network? I am only able to get the exact same output for any input that i pass through the network?

Appreciate your time.

**Comment by baumgach** [comment]
Hi, 

I have added an example for loading the weights and classifying some example images. Please have a look at the new file `example.py`. 

Cheers, Christian

**Comment by gravity1989** [comment]
Thanks @baumgach !
