### ISSUE TITLE
Saliency map

### ISSUE THREAD

**Issue by KunkyuLee** [baumgach/SonoNet-weights#2]
I want to know how to implement saliency map to detect objects and box them.

In keras, 
after saliency = K.gradient(K.sum(model.output), model.input),
K.function([model.input, K.learning_phase()], saliency).

But I can't get what I want to show.
How do you implement saliency map?

**Comment by baumgach** [comment]
Unfortunately, the code for this project cannot be made public. But you can find some simple implementation here: https://github.com/Lasagne/Recipes/blob/master/examples/Saliency%20Maps%20and%20Guided%20Backpropagation.ipynb
